create table herolist (
	id INT,
	name TEXT,
	attribute TEXT,
	attackrange TEXT,
	complexity TEXT,
	carrypower TEXT,
	supportpower TEXT
);

INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('1','abaddon','strength','melee','easy','weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('2','alchemist','strength','melee','easy','medium','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('3','axe','strength','melee','easy','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('4','beastmaster','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('5','brewmaster','strength','melee','hard','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('6','bristleback','strength','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('7','centaur','strength','melee','easy','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('8','chaos knight','strength','melee','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('9','clockwerk','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('10','doom','strength','melee','medium','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('11','dragon knight','strength','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('12','earth spirit','strength','melee','hard','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('13','earth shaker','strength','melee','medium','very weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('14','elder titan','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('15','huskar','strength','ranged','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('16','io','strength','ranged','hard','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('17','kunkka','strength','melee','medium','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('18','legion comander','strength','melee','easy','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('19','lifestealer','strength','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('20','lycan','strength','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('21','magnus','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('22','night stalker','strength','melee','easy','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('23','omniknight','strength','melee','easy','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('24','phoenix','strength','melee','medium','very weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('25','pudge','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('26','sand king','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('27','slardar','strength','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('28','spirit breaker','strength','melee','easy','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('29','sven','strength','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('30','tidehunter','strength','melee','easy','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('31','timbersaw','strength','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('32','tiny','strength','melee','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('33','treant protector','strength','melee','medium','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('34','tusk','strength','melee','easy','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('35','underlord','strength','melee','medium','very weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('36','undying','strength','melee','easy','very weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('37','wraith king','strength','melee','easy','medium','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('38','antimage','agility','melee','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('39','arc warden','agility','ranged','hard','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('40','bloodseeker','agility','melee','easy','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('41','bounty hunter','agility','melee','easy','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('42','broodmother','agility','melee','medium','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('43','clinkz','agility','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('44','drow ranger','agility','ranged','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('45','ember spirit','agility','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('46','faceless void','agility','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('47','gyrocopter','agility','ranged','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('48','juggernaut','agility','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('49','lone druid','agility','ranged','hard','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('50','luna','agility','ranged','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('51','medusa','agility','ranged','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('52','meepo','agility','melee','hard','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('53','mirana','agility','ranged','medium','weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('54','monkey king','agility','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('55','morphling','agility','ranged','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('56','naga siren','agility','melee','medium','strong','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('57','nyx assassin','agility','melee','medium','very weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('58','pangolier','agility','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('59','phantom assassin','agility','melee','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('60','phantom lancer','agility','melee','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('61','razor','agility','ranged','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('62','riki','agility','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('63','shadow fiend','agility','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('64','slark','agility','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('65','sniper','agility','ranged','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('66','spectre','agility','ranged','medium','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('67','templar assassin','agility','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('68','terrorblade','agility','melee','medium','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('69','troll warlord','agility','melee','medium','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('70','ursa','agility','melee','easy','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('71','vengeful spirit','agility','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('72','venomancer','agility','ranged','easy','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('73','viper','agility','ranged','easy','weak','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('74','weaver','agility','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('75','ancient apparition','intelligence','ranged','medium','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('76','bane','intelligence','ranged','medium','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('77','batrider','intelligence','ranged','medium','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('78','chen','intelligence','ranged','hard','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('79','crystal maiden','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('80','dark seer','intelligence','melee','easy','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('81','dark willow','intelligence','ranged','medium','weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('82','dazzle','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('83','death prophet','intelligence','ranged','easy','medium','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('84','disruptor','intelligence','ranged','medium','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('85','enchantress','intelligence','ranged','medium','medium','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('86','enigma','intelligence','ranged','medium','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('87','invoker','intelligence','ranged','hard','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('88','jakiro','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('89','kotl','intelligence','ranged','medium','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('90','lehsrac','intelligence','ranged','easy','weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('91','lich','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('92','lina','intelligence','ranged','easy','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('93','lion','intelligence','ranged','easy','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('94','nature prophet','intelligence','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('95','necrophos','intelligence','ranged','easy','strong','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('96','ogre magi','intelligence','melee','easy','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('97','oracle','intelligence','ranged','hard','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('98','outworld devourer','intelligence','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('99','puck','intelligence','ranged','medium','medium','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('100','pugna','intelligence','ranged','medium','medium','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('101','queen of pain','intelligence','ranged','medium','medium','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('102','rubick ','intelligence','ranged','hard','weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('103','shadow demon','intelligence','ranged','medium','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('104','shadow shaman','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('105','silencer','intelligence','ranged','medium','medium','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('106','skywrath mage','intelligence','ranged','easy','medium','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('107','storm spirit','intelligence','ranged','hard','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('108','techies','intelligence','ranged','medium','very weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('109','tinker','intelligence','ranged','medium','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('110','visage','intelligence','ranged','hard','very weak','weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('111','warlock','intelligence','ranged','easy','weak','medium');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('112','windranger','intelligence','ranged','medium','strong','very weak');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('113','winter weavern ','intelligence','ranged','medium','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('114','witch doctor ','intelligence','ranged','easy','very weak','strong');
INSERT INTO herolist (id,name,attribute,attackrange,complexity,carrypower,supportpower) VALUES ('115','zeus','intelligence','ranged','easy','medium','weak');